apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrievedata
  labels:
    app: retrievedata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retrievedata
  template:
    metadata:
      labels:
        app: retrievedata
    spec:
      containers:
      - name: app
        image: ms/retrievedata
        imagePullPolicy: Never
